### ISSUE TITLE
Generate Bug

### ISSUE THREAD

**Issue by lesbenito220** [Beta-testers/FPGACAT#14]
The generate button in the ROM section does not work for me. It seems to just stay stuck down but doesn't actually generate any of the code. I can only get it unstuck by quitting and restarting the app. This is for version 2.74 of the application. This is the first time I've use the new tester and this version of the app. 

I verified that if I use the old tester and verions 2.5 of the app it works correctly. 

I am using Window 7 (32-bit version)

**Comment by bperkins011** [comment]
I have the exact same issue..  I have to go back to 2.62 to generate all the ROM checksums.  I've been meaning to message about it.

**Comment by fcawth** [comment]
Fixed for the next release.  I will try to get it out soon.
